project:
  type: book
  output-dir: .

book:
  title: "AutoScore: An Interpretable Machine Learning-Based Automatic Clinical Score Generator"
  author: "Feng Xie, Yilin Ning, Han Yuan, Mingxuan Liu, Seyed Ehsan Saffari, Siqi Li, Bibhas Chakraborty, Nan Liu"
  date: today
  date-format: iso
  chapters:
    - index.qmd
    - 01-related_papers.qmd
    - 03-data_processing.qmd
    - 02-desc_analysis.qmd
    - 04-autoscore.qmd
    - 05-autoscore_survival.qmd
    - 06-autoscore_ordinal.qmd

format:
  html:
    theme: simplex
    css: custom.css
    number-sections: true
    always_allow_html: true
    code-copy: true
    number-depth: 3
    page-layout: full
